### ISSUE TITLE
generate_ios_framework

### ISSUE THREAD

**Issue by spdd** [jhondge/torch4ios#1]
Hi @jhondge! I'm trying to build Torch framework from your repo because original repo is quite old and outdated, when I generate_ios_framework I got build error:

`/Applications/Xcode.app/Contents/Developer/usr/bin/xcrun  --sdk iphoneos clang -arch armv7 -miphoneos-version-min=6.0 -O2  -D__NEON__ -mfpu=neon -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -pagezero_size 10000 -image_base 100000000  CMakeFiles/luajit.dir/src/luajit.c.o CMakeFiles/luajit.dir/src/ljamalg.c.o CMakeFiles/luajit.dir/lj_vm.S.o  -o luajit  /opt/local/lib/libreadline.dylib /usr/lib/libdl.dylib -lm 
ld: warning: ignoring -seg1addr 0x100000000.  Address out of range.
ld: warning: object file (CMakeFiles/luajit.dir/lj_vm.S.o) was built for newer iOS version (9.3) than being linked (6.0)
ld: warning: ignoring file /opt/local/lib/libreadline.dylib, file was built for x86_64 which is not the architecture being linked (armv7): /opt/local/lib/libreadline.dylib
Undefined symbols for architecture armv7:
  "_add_history", referenced from:
      _dotty in luajit.c.o
  "_read_history", referenced from:
      _dotty in luajit.c.o
  "_readline", referenced from:
      _pushline in luajit.c.o
  "_rl_attempted_completion_function", referenced from:
      _dotty in luajit.c.o
  "_rl_completer_quote_characters", referenced from:
      _dotty in luajit.c.o
  "_rl_completer_word_break_characters", referenced from:
      _dotty in luajit.c.o
  "_rl_completion_suppress_append", referenced from:
      _lua_rl_complete in luajit.c.o
  "_rl_initialize", referenced from:
      _dotty in luajit.c.o
  "_rl_readline_name", referenced from:
      _dotty in luajit.c.o
  "_stifle_history", referenced from:
      _dotty in luajit.c.o
  "_using_history", referenced from:
      _dotty in luajit.c.o
  "_write_history", referenced from:
      _dotty in luajit.c.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [distro/exe/luajit-rocks/luajit-2.1/luajit] Error 1
make[1]: *** [distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/all] Error 2`

What can I solve that?

**Comment by jhondge** [comment]
Hi @spdd It's Readline library can't found on iOS which reference in luajit2.1 CMakeLists.txt, So you just remote it or update my distro with upstream branch and exe/luajit-rocks with ios_build branch, it was resolved now.

**Comment by spdd** [comment]
Thanks @jhondge It worked, but finally I got shared libs: libluaT.so, libnnx.so, libpaths.so, libTH.so, libTHNN.so and libtorch.so only libluajit.a is static. I'm not familiar with cmake but I found CMakeLists.txt for libluaT libTH  and change strings from ADD_LIBRARY(... SHARED ${src}) to ADD_LIBRARY(... STATIC ${src}) after build I got libluaT.a and libTH.a, I couldn't find it for other libs.
Where I can change cmake files for build only static libraries?

**Comment by spdd** [comment]
Finally I got framework :) But I have some troubles with torch-ios example projects...

**Comment by spdd** [comment]
I fixed issue again) but I noticed that libnn.a not building after generate script finished and therefore I got this issue: 
`Undefined symbols for architecture armv7:
  "_luaopen_libnn", referenced from:`
THNN.a is nn right? What we need generate libnn.a for?

**Comment by jhondge** [comment]
@spdd You don't need call luaopen_libnn again, comment that method and be sure xcode other linker flag contain -all_load (avoid xcode remove unuse symbol)

**Comment by spdd** [comment]
Ok I did it, but still not working: 
`XOR_Example_Pretrained.app/xor_lua/xor_model.net
Loaded Neural Network -- Success
XOR_Example_Pretrained[915:247264] error running function f': ..._Pretrained.app/Torch.framework/Resources/torch/File.lua:343: unknown Torch class <nn.Sequential>`

**Comment by spdd** [comment]
I added require 'nn' but still example model not loaded (unknown object) I think it depends on platform

**Comment by spdd** [comment]
finally I loaded model as ascii text file, but I have many errors like `THNN_DoubleHardTanh_updateOutput...ple_Pretrained.app/Torch.framework/Resources/nn/THNN.lua:108: dlsym(RTLD_DEFAULT, THNN_DoubleHardTanh_updateOutput): symbol not found`

all errors point to THNN.lua:108 line

**Comment by jhondge** [comment]
@spdd Do you have set -all_load  to "other linker flag" yet ? you must do it otherwise THNN library can't be link to your application, because it's called by lua (don't compile)

**Comment by spdd** [comment]
@jhondge Yes I set the linker flag, I think THNN linked but not full, because I could to load xor_model.txt model but the model can't forward a tensor

**Comment by jhondge** [comment]
@spdd You can use command `nm Torch` to check your framework Torch does contain symbol what that symbol not found, or you can use this `void *address =  dlsym(RTLD_DEFAULT, "THNN_DoubleAbs_updateGradInput");NSLog(@"address:%p",address);` check that on ios code.

**Comment by spdd** [comment]
Thanks @jhondge I checked several functions with dlsym and they all returned 0x0, though they contains in Torch static library. I think occurs something wrong when building framework.

**Comment by jhondge** [comment]
It's Readline library can't find on iOS which reference in luajit 2.1 CMakelists.txt ,So just remove it or update my distro. It was resolved now

发自我的 iPhone

在 2016年10月21日，16:32，spdd <notifications@github.com<mailto:notifications@github.com>> 写道：

Hi @jhondgehttps://github.com/jhondge! I'm trying to build Torch framework from your repo because original repo is quite old and outdated, when I generate_ios_framework I got build error:

/Applications/Xcode.app/Contents/Developer/usr/bin/xcrun --sdk iphoneos clang -arch armv7 -miphoneos-version-min=6.0 -O2 -D__NEON__ -mfpu=neon -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -pagezero_size 10000 -image_base 100000000 CMakeFiles/luajit.dir/src/luajit.c.o CMakeFiles/luajit.dir/src/ljamalg.c.o CMakeFiles/luajit.dir/lj_vm.S.o -o luajit /opt/local/lib/libreadline.dylib /usr/lib/libdl.dylib -lm
ld: warning: ignoring -seg1addr 0x100000000. Address out of range.
ld: warning: object file (CMakeFiles/luajit.dir/lj_vm.S.o) was built for newer iOS version (9.3) than being linked (6.0)
ld: warning: ignoring file /opt/local/lib/libreadline.dylib, file was built for x86_64 which is not the architecture being linked (armv7): /opt/local/lib/libreadline.dylib
Undefined symbols for architecture armv7:
"_add_history", referenced from:
_dotty in luajit.c.o
"_read_history", referenced from:
_dotty in luajit.c.o
"_readline", referenced from:
_pushline in luajit.c.o
"_rl_attempted_completion_function", referenced from:
_dotty in luajit.c.o
"_rl_completer_quote_characters", referenced from:
_dotty in luajit.c.o
"_rl_completer_word_break_characters", referenced from:
_dotty in luajit.c.o
"_rl_completion_suppress_append", referenced from:
_lua_rl_complete in luajit.c.o
"_rl_initialize", referenced from:
_dotty in luajit.c.o
"_rl_readline_name", referenced from:
_dotty in luajit.c.o
"_stifle_history", referenced from:
_dotty in luajit.c.o
"_using_history", referenced from:
_dotty in luajit.c.o
"_write_history", referenced from:
_dotty in luajit.c.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [distro/exe/luajit-rocks/luajit-2.1/luajit] Error 1
make[1]: **\* [distro/exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/all] Error 2

What can I solve that?

―

**Comment by spdd** [comment]
I updated xCode and now it worked for me (all symbols from lib loaded). Thanks @jhondge !
